version: '3.2'

services:
  jqapi:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=jqapi.flexibledev.com
    - NGINX_PORT=80,443